# Generated by Django 3.0.6 on 2020-05-21 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm_tools_web', '0004_auto_20200507_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raid', models.CharField(choices=[('MC', 'Molten Core'), ('BWL', 'Blackwing Lair'), ('ZG', "Zul'gurub")], max_length=5)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warcraft_logs_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warcraft_logs_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('started_on', models.DateTimeField()),
                ('ended_on', models.DateTimeField()),
                ('zone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BossFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kill', models.BooleanField()),
                ('attendance', models.ManyToManyField(to='mm_tools_web.Character')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_tools_web.Boss')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_tools_web.Raid')),
            ],
        ),
    ]
