# Generated by Django 3.0.6 on 2020-05-21 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_tools_web', '0005_boss_bossfight_character_raid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossfight',
            name='ended_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 3, 32, 10, 941542)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bossfight',
            name='started_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 3, 32, 16, 653697)),
            preserve_default=False,
        ),
    ]
