# Generated by Django 3.0.6 on 2020-05-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_tools_web', '0006_auto_20200521_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boss',
            name='raid',
        ),
        migrations.AddField(
            model_name='boss',
            name='warcraft_logs_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
