# Generated by Django 3.0.6 on 2020-05-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_tools_web', '0007_auto_20200521_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossfight',
            name='fight_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
