# Generated by Django 3.0.6 on 2020-05-21 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mm_tools_web', '0009_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LootAwarded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_tools_web.Character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_tools_web.Item')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mm_tools_web.Raid')),
            ],
        ),
    ]
