# Generated by Django 3.0.6 on 2020-08-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_tools_web', '0010_lootawarded'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='lootawarded',
            options={'ordering': ['-raid__started_on', 'character__name'], 'verbose_name_plural': 'Loot awarded'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'permissions': [('can_export_priorities', 'Can export priorities')], 'verbose_name_plural': 'Priorities'},
        ),
        migrations.AlterModelOptions(
            name='raid',
            options={'ordering': ['-started_on']},
        ),
        migrations.AlterField(
            model_name='item',
            name='zone',
            field=models.CharField(choices=[('MC', 'Molten Core'), ('BWL', 'Blackwing Lair'), ('ZG', "Zul'gurub"), ('ONY', 'Onyxia'), ('AQ20', "Temple of Ahn'Qiraj"), ('AQ40', "Ruins of Ahn'Qiraj")], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='lootawarded',
            unique_together={('item', 'character', 'raid')},
        ),
    ]
