# Generated by Django 3.0.6 on 2020-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm_tools_web', '0012_import_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='zone',
            field=models.CharField(choices=[('MC', 'Molten Core'), ('BWL', 'Blackwing Lair'), ('ZG', "Zul'gurub"), ('ONY', 'Onyxia'), ('AQ20', "Ruins of Ahn'Qiraj"), ('AQ40', "Temple of Ahn'Qiraj"), ('NAXX', 'Naxx')], max_length=5),
        ),
        migrations.CreateModel(
            name='ItemTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('items', models.ManyToManyField(to='mm_tools_web.Item')),
            ],
        ),
    ]
